words: set[str] = {
    'have',
    'do',
    'say',
    'get',
    'make',
    'go',
    'know',
    'take',
    'see',
    'come',
    'think',
    'look',
    'want',
    'give',
    'use',
    'find',
    'tell',
    'ask',
    'work',
    'seem',
    'feel',
    'try',
    'leave',
    'call',
    'person',
    'man',
    'woman',
    'child',
    'time',
    'year',
    'week',
    'day',
    'way',
    'thing',
    'world',
    'life',
    'hand',
    'part',
    'eye',
    'place',
    'work',
    'case',
    'point',
    'government',
    'company',
    'number',
    'group',
    'problem',
    'fact',
    'good',
    'new',
    'first',
    'last',
    'long',
    'great',
    'little',
    'own',
    'other',
    'old',
    'right',
    'big',
    'high',
    'different',
    'small',
    'large',
    'next',
    'early',
    'young',
    'important',
    'few',
    'public',
    'bad',
    'same',
    'able',
    'to',
    'of',
    'in',
    'for',
    'on',
    'with',
    'at',
    'by',
    'from',
    'up',
    'about',
    'into',
    'over',
    'after',
    'computer',
    'hacker',
    'database',
    'smartphone',
    'internet',
    'develop',
    'user',
    'headphone',
    'soymilk',
    'document',
    'monitor',
    'science',
    'software',
    'sercurity',
    'electrical engineering',
    'professor',
    'nthu',
    'virus',
    'firewall',
    'if',
    'hardware',
    'board game',
    'python',
    'programming language',
    'google cloud',
    'water bottle',
    'hello world',
    'apple juice',
    'kids hacker camp',
    'environment',
    'ethernet',
    'kernel',
    'packet',
    'pixel',
    'protocol',
    'prototype',
    'definition',
    'storage',
    'microcontroller',
    'controller',
    'client',
    'server',
    'application',
    'program',
    'boolean',
    'buffer',
    'error',
    'process',
    'binary',
    'bandwidth',
    'hexadecimal',
    'array',
    'analog',
    'digital',
    'frequency',
    'technology',
    'central processing unit',
    'device',
    'alphabetic',
    'organization',
    'information',
    'important',
    'markdown',
    'javascript',
    'researcher',
    'inclusive',
    'Inheritance',
    'subclass',
    'decorator',
    'design pattern',
    'generics',
    'typescript',
    'playground',
    'compiler',
    'header',
    'interpreter',
    'transpiler',
    'generation',
    'executable',
    'traditional chinese',
    'least significant bit',
    'common gateway interface',
    'control panel',
    'disc operating system',
    'solid state drive',
    'file allocation table',
    'integrated development environment',
    'local area network',
    'universal serial bus',
    'transmission control protocol',
    'internet protocol',
}
